In [19]:
import pandas as pd
import numpy as np

In [20]:
def Clean_data(data_file):
    for i in range(len(data_file)):
        a = ''.join(filter(str.isdigit, data_file.loc[i, 'Temp']))
        data_file.loc[i, 'Temp'] = a
        if data_file.loc[i][3] == "No wind":
            data_file.loc[i, 'Wind'] = "0"
        else:
            b = ''.join(filter(str.isdigit, data_file.loc[i][3]))
            data_file.loc[i, 'Wind'] = b
        c = ''.join(filter(str.isdigit, data_file.loc[i][4]))
        data_file.loc[i, 'Humidity'] = c
        d = ''.join(filter(str.isdigit, data_file.loc[i][5]))
        data_file.loc[i, 'Barometer'] = d
        if type(data_file.loc[i, 'Visibility']) == str:
            e = ''.join(filter(str.isdigit, data_file.loc[i][6]))
            data_file.loc[i, 'Visibility'] = e
        else:
            data_file.loc[i, 'Visibility'] = data_file.loc[i, 'Visibility']
    data_file['Visibility'] = data_file['Visibility'].fillna(100)
    return data_file

## Làm sạch dữ liệu 1000 samples

In [21]:
data_file_1000 = pd.read_excel('data_1000_samples.xlsx')
data_file_1000

,Time,Temp,Weather,Wind,Humidity,Barometer,Visibility,Day,Month,Year
0,12:00 SA,22 °C,Passing clouds.,4 km/h,88%,1016 mbar,NaN,1,3,2022
1,12:30 SA,22 °C,Passing clouds.,4 km/h,88%,1015 mbar,NaN,1,3,2022
2,1:00 SA,22 °C,Passing clouds.,4 km/h,83%,1015 mbar,NaN,1,3,2022
3,1:30 SA,21 °C,Passing clouds.,4 km/h,88%,1015 mbar,8 km,1,3,2022
4,2:00 SA,21 °C,Passing clouds.,2 km/h,88%,1015 mbar,8 km,1,3,2022
...,...,...,...,...,...,...,...,...,...,...
996,5:00 CH,28 °C,Passing clouds.,19 km/h,79%,1009 mbar,NaN,22,3,2022
997,5:30 CH,28 °C,Passing clouds.,13 km/h,79%,1009 mbar,NaN,22,3,2022
998,6:00 CH,27 °C,Passing clouds.,11 km/h,84%,1009 mbar,NaN,22,3,2022
999,6:30 CH,27 °C,Passing clouds.,11 km/h,84%,1009 mbar,NaN,22,3,2022
1000,7:00 CH,27 °C,Passing clouds.,13 km/h,84%,1009 mbar,NaN,22,3,2022

In [22]:
data_file_1000 = Clean_data(data_file_1000)
data_file_1000

,Time,Temp,Weather,Wind,Humidity,Barometer,Visibility,Day,Month,Year
0,12:00 SA,22,Passing clouds.,4,88,1016,100,1,3,2022
1,12:30 SA,22,Passing clouds.,4,88,1015,100,1,3,2022
2,1:00 SA,22,Passing clouds.,4,83,1015,100,1,3,2022
3,1:30 SA,21,Passing clouds.,4,88,1015,8,1,3,2022
4,2:00 SA,21,Passing clouds.,2,88,1015,8,1,3,2022
...,...,...,...,...,...,...,...,...,...,...
996,5:00 CH,28,Passing clouds.,19,79,1009,100,22,3,2022
997,5:30 CH,28,Passing clouds.,13,79,1009,100,22,3,2022
998,6:00 CH,27,Passing clouds.,11,84,1009,100,22,3,2022
999,6:30 CH,27,Passing clouds.,11,84,1009,100,22,3,2022
1000,7:00 CH,27,Passing clouds.,13,84,1009,100,22,3,2022

In [23]:
data_file_1000.to_excel('data_1000_samples_clean.xlsx', index=False)

## Làm sạch dữ liệu 10000 samples

In [24]:
data_file_10000 = pd.read_excel('data_10000_samples.xlsx')
data_file_10000

,Time,Temp,Weather,Wind,Humidity,Barometer,Visibility,Day,Month,Year
0,12:00 SA,22 °C,Passing clouds.,4 km/h,88%,1016 mbar,NaN,1,3,2022
1,12:30 SA,22 °C,Passing clouds.,4 km/h,88%,1015 mbar,NaN,1,3,2022
2,1:00 SA,22 °C,Passing clouds.,4 km/h,83%,1015 mbar,NaN,1,3,2022
3,1:30 SA,21 °C,Passing clouds.,4 km/h,88%,1015 mbar,8 km,1,3,2022
4,2:00 SA,21 °C,Passing clouds.,2 km/h,88%,1015 mbar,8 km,1,3,2022
...,...,...,...,...,...,...,...,...,...,...
9996,6:00 CH,26 °C,Partly cloudy.,22 km/h,89%,1011 mbar,7 km,24,10,2022
9997,7:00 CH,25 °C,Light rain. Partly cloudy.,2 km/h,89%,1012 mbar,6 km,24,10,2022
9998,7:30 CH,25 °C,Light rain. Partly cloudy.,2 km/h,89%,1012 mbar,6 km,24,10,2022
9999,8:30 CH,25 °C,Light rain. Partly cloudy.,9 km/h,89%,1013 mbar,6 km,24,10,2022
10000,9:00 CH,25 °C,Passing clouds.,13 km/h,89%,1013 mbar,8 km,24,10,2022

In [25]:
data_file_10000 = Clean_data(data_file_10000)
data_file_10000

,Time,Temp,Weather,Wind,Humidity,Barometer,Visibility,Day,Month,Year
0,12:00 SA,22,Passing clouds.,4,88,1016,100,1,3,2022
1,12:30 SA,22,Passing clouds.,4,88,1015,100,1,3,2022
2,1:00 SA,22,Passing clouds.,4,83,1015,100,1,3,2022
3,1:30 SA,21,Passing clouds.,4,88,1015,8,1,3,2022
4,2:00 SA,21,Passing clouds.,2,88,1015,8,1,3,2022
...,...,...,...,...,...,...,...,...,...,...
9996,6:00 CH,26,Partly cloudy.,22,89,1011,7,24,10,2022
9997,7:00 CH,25,Light rain. Partly cloudy.,2,89,1012,6,24,10,2022
9998,7:30 CH,25,Light rain. Partly cloudy.,2,89,1012,6,24,10,2022
9999,8:30 CH,25,Light rain. Partly cloudy.,9,89,1013,6,24,10,2022
10000,9:00 CH,25,Passing clouds.,13,89,1013,8,24,10,2022

In [26]:
data_file_10000.to_excel('data_10000_samples_clean.xlsx', index=False)